// Code generated by protoc-gen-go.
// source: cesar.proto
// DO NOT EDIT!

/*
Package cesar is a generated protocol buffer package.

It is generated from these files:
	cesar.proto

It has these top-level messages:
	FileRequest
	CreateSymLinkRequest
	FileResponse
	GetBuildAttrRequest
	SetBuildAttrRequest
	BuildAttrResponse
*/
package cesar

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The Request message containing information about the file
type FileRequest struct {
	Path     string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Contents []byte `protobuf:"bytes,2,opt,name=contents,proto3" json:"contents,omitempty"`
}

func (m *FileRequest) Reset()                    { *m = FileRequest{} }
func (m *FileRequest) String() string            { return proto.CompactTextString(m) }
func (*FileRequest) ProtoMessage()               {}
func (*FileRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *FileRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *FileRequest) GetContents() []byte {
	if m != nil {
		return m.Contents
	}
	return nil
}

type CreateSymLinkRequest struct {
	Name        string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	OrginalFile string `protobuf:"bytes,2,opt,name=orginal_file,json=orginalFile" json:"orginal_file,omitempty"`
}

func (m *CreateSymLinkRequest) Reset()                    { *m = CreateSymLinkRequest{} }
func (m *CreateSymLinkRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateSymLinkRequest) ProtoMessage()               {}
func (*CreateSymLinkRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateSymLinkRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateSymLinkRequest) GetOrginalFile() string {
	if m != nil {
		return m.OrginalFile
	}
	return ""
}

// The Response for when a file was built
type FileResponse struct {
	File    string `protobuf:"bytes,1,opt,name=file" json:"file,omitempty"`
	Success bool   `protobuf:"varint,2,opt,name=success" json:"success,omitempty"`
	Error   string `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
}

func (m *FileResponse) Reset()                    { *m = FileResponse{} }
func (m *FileResponse) String() string            { return proto.CompactTextString(m) }
func (*FileResponse) ProtoMessage()               {}
func (*FileResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *FileResponse) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

func (m *FileResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *FileResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type GetBuildAttrRequest struct {
}

func (m *GetBuildAttrRequest) Reset()                    { *m = GetBuildAttrRequest{} }
func (m *GetBuildAttrRequest) String() string            { return proto.CompactTextString(m) }
func (*GetBuildAttrRequest) ProtoMessage()               {}
func (*GetBuildAttrRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type SetBuildAttrRequest struct {
	Folder  string `protobuf:"bytes,1,opt,name=folder" json:"folder,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	Flavor  string `protobuf:"bytes,3,opt,name=flavor" json:"flavor,omitempty"`
	Clean   bool   `protobuf:"varint,4,opt,name=clean" json:"clean,omitempty"`
}

func (m *SetBuildAttrRequest) Reset()                    { *m = SetBuildAttrRequest{} }
func (m *SetBuildAttrRequest) String() string            { return proto.CompactTextString(m) }
func (*SetBuildAttrRequest) ProtoMessage()               {}
func (*SetBuildAttrRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SetBuildAttrRequest) GetFolder() string {
	if m != nil {
		return m.Folder
	}
	return ""
}

func (m *SetBuildAttrRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *SetBuildAttrRequest) GetFlavor() string {
	if m != nil {
		return m.Flavor
	}
	return ""
}

func (m *SetBuildAttrRequest) GetClean() bool {
	if m != nil {
		return m.Clean
	}
	return false
}

type BuildAttrResponse struct {
	Folder  string `protobuf:"bytes,1,opt,name=folder" json:"folder,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	Flavor  string `protobuf:"bytes,3,opt,name=flavor" json:"flavor,omitempty"`
	Clean   bool   `protobuf:"varint,4,opt,name=clean" json:"clean,omitempty"`
}

func (m *BuildAttrResponse) Reset()                    { *m = BuildAttrResponse{} }
func (m *BuildAttrResponse) String() string            { return proto.CompactTextString(m) }
func (*BuildAttrResponse) ProtoMessage()               {}
func (*BuildAttrResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *BuildAttrResponse) GetFolder() string {
	if m != nil {
		return m.Folder
	}
	return ""
}

func (m *BuildAttrResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *BuildAttrResponse) GetFlavor() string {
	if m != nil {
		return m.Flavor
	}
	return ""
}

func (m *BuildAttrResponse) GetClean() bool {
	if m != nil {
		return m.Clean
	}
	return false
}

func init() {
	proto.RegisterType((*FileRequest)(nil), "cesar.FileRequest")
	proto.RegisterType((*CreateSymLinkRequest)(nil), "cesar.CreateSymLinkRequest")
	proto.RegisterType((*FileResponse)(nil), "cesar.FileResponse")
	proto.RegisterType((*GetBuildAttrRequest)(nil), "cesar.GetBuildAttrRequest")
	proto.RegisterType((*SetBuildAttrRequest)(nil), "cesar.SetBuildAttrRequest")
	proto.RegisterType((*BuildAttrResponse)(nil), "cesar.BuildAttrResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Cesar service

type CesarClient interface {
	BuildFile(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*FileResponse, error)
	CreateSymLink(ctx context.Context, in *CreateSymLinkRequest, opts ...grpc.CallOption) (*FileResponse, error)
	SetBuildAttributes(ctx context.Context, in *SetBuildAttrRequest, opts ...grpc.CallOption) (*BuildAttrResponse, error)
	GetBuildAttributes(ctx context.Context, in *GetBuildAttrRequest, opts ...grpc.CallOption) (*BuildAttrResponse, error)
}

type cesarClient struct {
	cc *grpc.ClientConn
}

func NewCesarClient(cc *grpc.ClientConn) CesarClient {
	return &cesarClient{cc}
}

func (c *cesarClient) BuildFile(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*FileResponse, error) {
	out := new(FileResponse)
	err := grpc.Invoke(ctx, "/cesar.Cesar/BuildFile", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cesarClient) CreateSymLink(ctx context.Context, in *CreateSymLinkRequest, opts ...grpc.CallOption) (*FileResponse, error) {
	out := new(FileResponse)
	err := grpc.Invoke(ctx, "/cesar.Cesar/CreateSymLink", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cesarClient) SetBuildAttributes(ctx context.Context, in *SetBuildAttrRequest, opts ...grpc.CallOption) (*BuildAttrResponse, error) {
	out := new(BuildAttrResponse)
	err := grpc.Invoke(ctx, "/cesar.Cesar/SetBuildAttributes", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cesarClient) GetBuildAttributes(ctx context.Context, in *GetBuildAttrRequest, opts ...grpc.CallOption) (*BuildAttrResponse, error) {
	out := new(BuildAttrResponse)
	err := grpc.Invoke(ctx, "/cesar.Cesar/GetBuildAttributes", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Cesar service

type CesarServer interface {
	BuildFile(context.Context, *FileRequest) (*FileResponse, error)
	CreateSymLink(context.Context, *CreateSymLinkRequest) (*FileResponse, error)
	SetBuildAttributes(context.Context, *SetBuildAttrRequest) (*BuildAttrResponse, error)
	GetBuildAttributes(context.Context, *GetBuildAttrRequest) (*BuildAttrResponse, error)
}

func RegisterCesarServer(s *grpc.Server, srv CesarServer) {
	s.RegisterService(&_Cesar_serviceDesc, srv)
}

func _Cesar_BuildFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CesarServer).BuildFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cesar.Cesar/BuildFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CesarServer).BuildFile(ctx, req.(*FileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cesar_CreateSymLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSymLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CesarServer).CreateSymLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cesar.Cesar/CreateSymLink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CesarServer).CreateSymLink(ctx, req.(*CreateSymLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cesar_SetBuildAttributes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetBuildAttrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CesarServer).SetBuildAttributes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cesar.Cesar/SetBuildAttributes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CesarServer).SetBuildAttributes(ctx, req.(*SetBuildAttrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cesar_GetBuildAttributes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBuildAttrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CesarServer).GetBuildAttributes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cesar.Cesar/GetBuildAttributes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CesarServer).GetBuildAttributes(ctx, req.(*GetBuildAttrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Cesar_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cesar.Cesar",
	HandlerType: (*CesarServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BuildFile",
			Handler:    _Cesar_BuildFile_Handler,
		},
		{
			MethodName: "CreateSymLink",
			Handler:    _Cesar_CreateSymLink_Handler,
		},
		{
			MethodName: "SetBuildAttributes",
			Handler:    _Cesar_SetBuildAttributes_Handler,
		},
		{
			MethodName: "GetBuildAttributes",
			Handler:    _Cesar_GetBuildAttributes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cesar.proto",
}

func init() { proto.RegisterFile("cesar.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 349 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x93, 0xbf, 0x6e, 0xe2, 0x40,
	0x10, 0xc6, 0x0f, 0x0e, 0x38, 0x18, 0xb8, 0xe2, 0x06, 0x2e, 0xb2, 0x9c, 0x86, 0xb8, 0xa2, 0xa2,
	0x48, 0xa4, 0x74, 0x29, 0x12, 0xa4, 0xd0, 0x90, 0xc6, 0x3c, 0x40, 0xb4, 0x98, 0x21, 0x59, 0x65,
	0xd9, 0x25, 0xbb, 0x6b, 0xa4, 0xbc, 0x4d, 0x1e, 0x35, 0xda, 0x3f, 0x20, 0x23, 0xa0, 0x48, 0x91,
	0x6e, 0xbf, 0xf1, 0xf8, 0xf7, 0x7d, 0x9e, 0x59, 0x43, 0xb7, 0x20, 0xc3, 0xf4, 0x78, 0xa3, 0x95,
	0x55, 0xd8, 0xf4, 0x22, 0xbb, 0x83, 0xee, 0x23, 0x17, 0x94, 0xd3, 0x7b, 0x49, 0xc6, 0x22, 0x42,
	0x63, 0xc3, 0xec, 0x6b, 0x52, 0x1b, 0xd6, 0x46, 0x9d, 0xdc, 0x9f, 0x31, 0x85, 0x76, 0xa1, 0xa4,
	0x25, 0x69, 0x4d, 0x52, 0x1f, 0xd6, 0x46, 0xbd, 0x7c, 0xaf, 0xb3, 0x27, 0x18, 0x4c, 0x34, 0x31,
	0x4b, 0xf3, 0x8f, 0xf5, 0x8c, 0xcb, 0xb7, 0x0a, 0x47, 0xb2, 0x35, 0xed, 0x38, 0xee, 0x8c, 0x57,
	0xd0, 0x53, 0xfa, 0x85, 0x4b, 0x26, 0x9e, 0x57, 0x5c, 0x90, 0x67, 0x75, 0xf2, 0x6e, 0xac, 0xb9,
	0x14, 0x59, 0x0e, 0xbd, 0x90, 0xc6, 0x6c, 0x94, 0x34, 0xe4, 0x30, 0xbe, 0x35, 0x62, 0xdc, 0x19,
	0x13, 0xf8, 0x63, 0xca, 0xa2, 0x20, 0x13, 0xd2, 0xb4, 0xf3, 0x9d, 0xc4, 0x01, 0x34, 0x49, 0x6b,
	0xa5, 0x93, 0xdf, 0xbe, 0x3d, 0x88, 0xec, 0x3f, 0xf4, 0xa7, 0x64, 0x1f, 0x4a, 0x2e, 0x96, 0xf7,
	0xd6, 0xea, 0x98, 0x30, 0x2b, 0xa1, 0x3f, 0x3f, 0x2e, 0xe3, 0x05, 0xb4, 0x56, 0x4a, 0x2c, 0x49,
	0x47, 0xcf, 0xa8, 0x9c, 0xeb, 0x96, 0xb4, 0xe1, 0x4a, 0xc6, 0xdc, 0x3b, 0xe9, 0xdf, 0x10, 0x6c,
	0xbb, 0xb7, 0x8d, 0xca, 0xa5, 0x29, 0x04, 0x31, 0x99, 0x34, 0x7c, 0xca, 0x20, 0x32, 0x03, 0xff,
	0x2a, 0x9e, 0xf1, 0x33, 0x7f, 0xd8, 0xf4, 0xfa, 0xb3, 0x0e, 0xcd, 0x89, 0x5b, 0x37, 0xde, 0x42,
	0xc7, 0xdb, 0xbb, 0x29, 0x23, 0x8e, 0xc3, 0x85, 0xa8, 0x5c, 0x80, 0xb4, 0x7f, 0x50, 0x0b, 0xf9,
	0xb2, 0x5f, 0x38, 0x81, 0xbf, 0x07, 0x7b, 0xc6, 0xcb, 0xd8, 0x77, 0x6a, 0xfb, 0xe7, 0x20, 0x33,
	0xc0, 0xea, 0xc8, 0xf9, 0xa2, 0xb4, 0x64, 0x30, 0x8d, 0xcd, 0x27, 0xb6, 0x91, 0x26, 0xf1, 0xd9,
	0xd1, 0xc8, 0x02, 0x6d, 0x7a, 0x9e, 0x36, 0xfd, 0x1e, 0x6d, 0xd1, 0xf2, 0x7f, 0xc5, 0xcd, 0x57,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xf3, 0x71, 0x8b, 0xa6, 0x24, 0x03, 0x00, 0x00,
}
